version: '3.0'
services:
  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5431:5432'
  redisdb:
    image: redis
    ports:
      - '6379:6379'

  backend:
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - BASE_URL=${BASE_URL}
    build:
      context: .
      args:
        - PORT:${PORT}
    volumes:
      - ./:/usr/app
    container_name: backend
    working_dir: /usr/app
    depends_on:
      - db
    ports: ['${PORT}:${PORT}']
    restart: always
